# Fayan Configuration File

# Database file path
database: ./data/fayan.db

# PageRank calculation interval (in minutes)
pagerank_interval: 10

# API server port
port: ":9090"

# Default nostr relays to connect to, used for searching uesrs' relay lists
relays:
  - wss://relay.damus.io/
  - wss://nos.lol/
  - wss://nostr.band/
  - wss://relay.primal.net/

# Seed public keys to start crawling from
seed_pubkeys:
  - 3efdaebb1d8923ebd99c9e7ace3b4194ab45512e2be79c1b7d68d9243e0d2681
  - 82341f882b6eabcd2ba7f1ef90aad961cf074af15b9ef44a09f9d2a8fbfbe6a2
  - 32e1827635450ebb3c5a7d12c1f8e7b2b514439ac10a67eef3d9fd9c5c68e245
  - 84dee6e676e5bb67b4ad4e042cf70cbd8681155db535942fcc6a0533858a7240
  - c48e29f04b482cc01ca1f9ef8c86ef8318c059e0e9353235162f080f26e14c11
  - 04c915daefee38317fa734444acee390a8269fe5810b2241e5e6dd343dfbecc9
  - eab0e756d32b80bcd464f3d844b8040303075a13eabc3599a762c9ac7ab91f4f
  - bd1e19980e2c91e6dc657e92c25762ca882eb9272d2579e221f037f93788de91
  - 4c96d763eb2fe01910f7e7220b7c7ecdbe1a70057f344b9f79c28af080c3ee30
  - 2e0a18aa76ff38eb464cf2d89132d78f57ddcc5ed438a9716e83f4c026c32045
  - 44189afbf0d25716de6af793dc61c113ecf56166481912ce14c2052db62f396c
  - 6e468422dfb74a5738702a8823b9b28168abab8655faacb6853cd0ee15deee93
  - 3bf0c63fcb93463407af97a5e5ee64fa883d107ef9e558472c4eb9aaaefa459d
  - a341f45ff9758f570a21b000c17d4e53a3a497c8397f26c0e6d61e5acffc7a98
  - 63fe6318dc58583cfe16810f86dd09e18bfd76aabc24a0081ce2856f330504ed
  - c4eabae1be3cf657bc1855ee05e69de9f059cb7a059227168b80b89761cbc4e0
  - 85080d3bad70ccdcd7f74c29a44f55bb85cbcd3dd0cbb957da1d215bdb931204
  - e88a691e98d9987c964521dff60025f60700378a4879180dcbbb4a5027850411
  - 84de35e2584d2b144aae823c9ed0b0f3deda09648530b93d1a2a146d1dea9864
  - 83e818dfbeccea56b0f551576b3fd39a7a50e1d8159343500368fa085ccd964b
  - 3f770d65d3a764a9c5cb503ae123e62ec7598ad035d836e2a810f3877a745b24
  - 472f440f29ef996e92a186b8d320ff180c855903882e59d50de1b8bd5669301e
  - 460c25e682fda7832b52d1f22d3d22b3176d972f60dcdc3212ed8c92ef85065c
  - 020f2d21ae09bf35fcdfb65decf1478b846f5f728ab30c5eaabcd6d081a81c3e
  - 1989034e56b8f606c724f45a12ce84a11841621aaf7182a1f6564380b9c4276b
  - f728d9e6e7048358e70930f5ca64b097770d989ccd86854fe618eda9c8a38106
  - bf2376e17ba4ec269d10fcc996a4746b451152be9031fa48e74553dde5526bce
  - fa984bd7dbb282f07e16e7ae87b26a2a7b9b90b7246a44771f0cf5ae58018f52
  - a4dbfdc6e7e27e33b04e8009cf15dd1df35d62a9b258e70c38166871a577c47a
  - cccfccb023231da836fd3f86605163fc41be51800fe13248da3125b35718521c
  - 50d94fc2d8580c682b071a542f8b1e31a200b0508bab95a33bef0855df281d63
  - 4379e76bfa76a80b8db9ea759211d90bb3e67b2202f8880cc4f5ffe2065061ad
  - b9e76546ba06456ed301d9e52bc49fa48e70a6bf2282be7a1ae72947612023dc
  - c49d52a573366792b9a6e4851587c28042fb24fa5625c6d67b8c95c8751aca15
  - 8617d46b5eefa61d07595915c096a19b9c6bb55909e67ea46a42c75f61cdae5d
  - 58c741aa630c2da35a56a77c1d05381908bd10504fdd2d8b43f725efa6d23196
  - aef0d6b212827f3ba1de6189613e6d4824f181f567b1205273c16895fdaf0b23
  - 59fbee7369df7713dbbfa9bbdb0892c62eba929232615c6ff2787da384cb770f
  - 1afe0c74e3d7784eba93a5e3fa554a6eeb01928d12739ae8ba4832786808e36d
  - c9b19ffcd43e6a5f23b3d27106ce19e4ad2df89ba1031dd4617f1b591e108965
  - 91c9a5e1a9744114c6fe2d61ae4de82629eaaa0fb52f48288093c7e7e036f832
  - edcd20558f17d99327d841e4582f9b006331ac4010806efa020ef0d40078e6da
  - 090254801a7e8e5085b02e711622f0dfa1a85503493af246aa42af08f5e4d2df
  - be1d89794bf92de5dd64c1e60f6a2c70c140abac9932418fee30c5c637fe9479
  - 7b3f7803750746f455413a221f80965eecb69ef308f2ead1da89cc2c8912e968
  - 0fe0b18b4dbf0e0aa40fcd47209b2a49b3431fc453b460efcf45ca0bd16bd6ac
  - 1577e4599dd10c863498fe3c20bd82aafaf829a595ce83c5cf8ac3463531b09b
  - 4523be58d395b1b196a9b8c82b038b6895cb02b683d0c253a955068dba1facd0
  - e1ff3bfdd4e40315959b08b4fcc8245eaa514637e1d4ec2ae166b743341be1af
  - e33fe65f1fde44c6dc17eeb38fdad0fceaf1cae8722084332ed1e32496291d42
  - 1bc70a0148b3f316da33fe3c89f23e3e71ac4ff998027ec712b905cd24f6a411
  - 00000000827ffaa94bfea288c3dfce4422c794fbb96625b6b31e9049f729d700
  - a5e93aef8e820cbc7ab7b6205f854b87aed4b48c5f6b30fbbeba5c99e40dcf3f
  - b83a28b7e4e5d20bd960c5faeb6625f95529166b8bdb045d42634a2f35919450
  - 76c71aae3a491f1d9eec47cba17e229cda4113a0bbb6e6ae1776d7643e29cafa
  - 1b11ed41e815234599a52050a6a40c79bdd3bfa3d65e5d4a2c8d626698835d6d
  - d307643547703537dfdef811c3dea96f1f9e84c8249e200353425924a9908cf8
  - d61f3bc5b3eb4400efdae6169a5c17cabf3246b514361de939ce4a1a0da6ef4a
  - fdd5e8f6ae0db817be0b71da20498c1806968d8a6459559c249f322fa73464a7
  - 6c237d8b3b120251c38c230c06d9e48f0d3017657c5b65c8c36112eb15c52aeb
  - fe7f6bc6f7338b76bbf80db402ade65953e20b2f23e66e898204b63cc42539a3
  - b99dbca0184a32ce55904cb267b22e434823c97f418f36daf5d2dff0dd7b5c27
  - a4cb51f4618cfcd16b2d3171c466179bed8e197c43b8598823b04de266cef110
  - 5a8e581f16a012e24d2a640152ad562058cb065e1df28e907c1bfa82c150c8ba
  - 2edbcea694d164629854a52583458fd6d965b161e3c48b57d3aff01940558884
  - c7dccba4fe4426a7b1ea239a5637ba40fab9862c8c86b3330fe65e9f667435f6
  - 19fefd7f39c96d2ff76f87f7627ae79145bc971d8ab23205005939a5a913bc2f
  - b7996c183e036df27802945b80bbdc8b0bf5971b6621a86bf3569c332117f07d
  - c48b5cced5ada74db078df6b00fa53fc1139d73bf0ed16de325d52220211dbd5
  - 3d2e51508699f98f0f2bdbe7a45b673c687fe6420f466dc296d90b908d51d594
  - aa55a479ad6934d0fd78f3dbd88515cd1ca0d7a110812e711380d59df7598935
  - ba2f394833658475e91680b898f9be0f1d850166c6a839dbe084d0266ad6e20a
  - 08c9d8c533064607a7f274961f7b375f3d2fc24ba11b77333c76c0d8377ab1f3
  - f8e6c64342f1e052480630e27e1016dce35fc3a614e60434fef4aa2503328ca9
  - 4657dfe8965be8980a93072bcfb5e59a65124406db0f819215ee78ba47934b3e
  - e1055729d51e037b3c14e8c56e2c79c22183385d94aadb32e5dc88092cd0fef4
  - 064de2497ce621aee2a5b4b926a08b1ca01bce9da85b0c714e883e119375140c
  - 805b34f708837dfb3e7f05815ac5760564628b58d5a0ce839ccbb6ef3620fac3
  - ee6ea13ab9fe5c4a68eaf9b1a34fe014a66b40117c50ee2a614f4cda959b6e74
  - c2622c916d9b90e10a81b2ba67b19bdfc5d6be26c25756d1f990d3785ce1361b
  - 6c535d95a8659b234d5a0805034f5f0a67e3c0ceffcc459f61f680fe944424bf
  - 74dcec31fd3b8cfd960bc5a35ecbeeb8b9cee8eb81f6e8da4c8067553709248d
  - 532d830dffe09c13e75e8b145c825718fc12b0003f61d61e9077721c7fff93cb
  - 826e9f895b81ab41a4522268b249e68d02ca81608def562a493cee35ffc5c759
  - d85f2436a8eca97bb8a5fa5c6e27efb51fb894f2c4f20804b57c24214550b6c4
  - 1739d937dc8c0c7370aa27585938c119e25c41f6c441a5d34c6d38503e3136ef
  - 8fe3f243e91121818107875d51bca4f3fcf543437aa9715150ec8036358939c5
  - b7ed68b062de6b4a12e51fd5285c1e1e0ed0e5128cda93ab11b4150b55ed32fc
  - b708f7392f588406212c3882e7b3bc0d9b08d62f95fa170d099127ece2770e5e
  - bd9eb657c25b4f6cda68871ce26259d1f9bc62420487e3224905b674a710a45a
  - a3b0ce5d70d0db22885706b2b1f144c6864a7e4828acff3f8f01ca6b3f54ad15
  - cf473ebe9736ba689c718de3d5ef38909bca57db3c38e3f9de7f5dadfc88ed6f
  - cbc5ef6b01cbd1ffa2cb95a954f04c385a936c1a86e1bb9ccdf2cf0f4ebeaccb
  - c037a6897df86bfd4df5496ca7e2318992b4766897fb18fbd1d347a4f4459f5e
  - 148d1366a5e4672b1321adf00321778f86a2371a4bdbe99133f28df0b3d32fa1
  - b9a537523bba2fcdae857d90d8a760de4f2139c9f90d986f747ce7d0ec0d173d
  - 34d2f5274f1958fcd2cb2463dabeaddf8a21f84ace4241da888023bf05cc8095
  - 8967f290cc7749fd3d232fb7110c05db746a31fce0635aeec4e111ad8bfc810d
  - 7fa56f5d6962ab1e3cd424e758c3002b8665f7b0d8dcee9fe9e288d7751ac194
  - e2ccf7cf20403f3f2a4a55b328f0de3be38558a7d5f33632fdaaefc726c1c8eb
